name: "Upsert PR Comment"
description: "Create or update a PR comment with a unique identifier"
inputs:
  comment-identifier:
    description: 'Unique string to identify the comment (e.g., "🚀 Build Validation Results")'
    required: true
  comment-body:
    description: "The full body of the comment to create or update"
    required: true
runs:
  using: "composite"
  steps:
    - name: Upsert comment
      uses: actions/github-script@v8
      env:
        COMMENT_IDENTIFIER: ${{ inputs.comment-identifier }}
        COMMENT_BODY: ${{ inputs.comment-body }}
      with:
        script: |
          const identifier = process.env.COMMENT_IDENTIFIER;
          const body = process.env.COMMENT_BODY;
          const hiddenIdentifier = `<!-- GITHUB_ACTION_COMMENT_ID: ${identifier} -->`;
          const newBody = `${body}\n\n${hiddenIdentifier}`;

          const { owner, repo } = context.repo;
          const issue_number = context.issue.number;

          // Find existing comment from this bot (with pagination for PRs with many comments)
          const comments = await github.paginate(github.rest.issues.listComments, {
            owner,
            repo,
            issue_number,
          });

          const botComment = comments.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes(hiddenIdentifier)
          );

          // Update existing comment or create new one
          if (botComment) {
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: botComment.id,
              body: newBody
            });
          } else {
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: newBody
            });
          }
